// <auto-generated />
namespace ChoiceYourBill.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_active_flag_in_poll : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_active_flag_in_poll));
        
        string IMigrationMetadata.Id
        {
            get { return "201806291354130_add_active_flag_in_poll"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
